version: '3.5'

services:
  nginx-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default-site:/usr/share/nginx/html
      - /docker/letsencrypt-docker-nginx/src/production/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/api-staging.joesweeny.co.uk/fullchain.pem:/etc/letsencrypt/live/api-staging.joesweeny.co.uk/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/api-staging.joesweeny.co.uk/privkey.pem:/etc/letsencrypt/live/api-staging.joesweeny.co.uk/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
    networks:
      - proxynet

networks:
  proxynet:
    name: gameplatform_network