version: 2
jobs:
  build:
    working_directory: ~/back-to-win
    machine:
      image: circleci/classic:201711-01

    steps:
      - checkout
      - deploy:
          name: Deploy to Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp ./staging/docker-compose.staging.yml root@${STAGING_SERVER}:~/nginx-proxy
              scp ./staging/nginx.conf root@${STAGING_SERVER}:~/nginx-proxy
              ssh root@${STAGING_SERVER} "docker-compose -f ./nginx-proxy/docker-compose.staging.yml up -d"
            fi