version: 2
jobs:
  build:
    working_directory: ~/nginx-proxy
    machine:
      image: circleci/classic:201711-01

    steps:
      - checkout
      - deploy:
          name: Deploy to Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              scp docker-compose.yml root@${SERVER}:~/nginx-proxy
              scp nginx.conf root@${SERVER}:~/nginx-proxy
              ssh root@${SERVER} "docker-compose -f ./nginx-proxy/docker-compose.yml up -d"
            fi
